room_list = [] #All active rooms
room_dict = {}
city_dict = {}
plane_list = [] #All planes possible
manufacturer_list = set()
game = None #Game Object
text_font = None
player = None
graphics_directory = 'graphics'